Estrutura de carregamento

In [1]:
import pandas as pd
import json

In [13]:
# Carregamento do arquivo bruto
with open("../data/raw/nyc311.json", "r", encoding="utf-8") as arquivo:
    dados = json.load(arquivo)

In [14]:
df = pd.DataFrame(dados)

Informações básicas dos dados

In [15]:
type(dados)

list

In [5]:
df.head()

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,...,vehicle_type,closed_date,resolution_description,resolution_action_updated_date,taxi_pick_up_location,facility_type,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment
0,70024641,2026-08-11T01:51:06.000,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,10451,2403 3 AVENUE,3 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,70021357,2026-08-11T01:50:41.000,NYPD,New York City Police Department,Illegal Parking,Posted Parking Sign Violation,Street/Sidewalk,10001,601 WEST 29 STREET,WEST 29 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,70022914,2026-08-11T01:50:01.000,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11435,95-07 CRESSKILL PLACE,CRESSKILL PLACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,70022802,2026-08-11T01:49:10.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,1-2 Family Dwelling,10466,3601 DE REIMER AVENUE,DE REIMER AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,70021703,2026-08-11T01:49:09.000,DSNY,Department of Sanitation,Illegal Posting,Poster or Sign,Sidewalk,10472,EAST 172 STREET,EAST 172 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.shape

(1000, 50)

In [7]:
df.columns.tolist()

['unique_key',
 'created_date',
 'agency',
 'agency_name',
 'complaint_type',
 'descriptor',
 'location_type',
 'incident_zip',
 'incident_address',
 'street_name',
 'cross_street_1',
 'cross_street_2',
 'intersection_street_1',
 'intersection_street_2',
 'address_type',
 'city',
 'landmark',
 'status',
 'community_board',
 'council_district',
 'police_precinct',
 'bbl',
 'borough',
 'x_coordinate_state_plane',
 'y_coordinate_state_plane',
 'open_data_channel_type',
 'park_facility_name',
 'park_borough',
 'latitude',
 'longitude',
 'location',
 ':id',
 ':version',
 ':created_at',
 ':updated_at',
 ':@computed_region_f5dn_yrer',
 ':@computed_region_yeji_bk3q',
 ':@computed_region_sbqj_enih',
 ':@computed_region_92fq_4b7q',
 'descriptor_2',
 'vehicle_type',
 'closed_date',
 'resolution_description',
 'resolution_action_updated_date',
 'taxi_pick_up_location',
 'facility_type',
 'bridge_highway_name',
 'bridge_highway_direction',
 'road_ramp',
 'bridge_highway_segment']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   unique_key                      1000 non-null   str
 1   created_date                    1000 non-null   str
 2   agency                          1000 non-null   str
 3   agency_name                     1000 non-null   str
 4   complaint_type                  1000 non-null   str
 5   descriptor                      1000 non-null   str
 6   location_type                   952 non-null    str
 7   incident_zip                    993 non-null    str
 8   incident_address                973 non-null    str
 9   street_name                     973 non-null    str
 10  cross_street_1                  898 non-null    str
 11  cross_street_2                  895 non-null    str
 12  intersection_street_1           898 non-null    str
 13  intersection_street_2           895 non-null    str
 14  address_type                    995 non-null    str
 15  city                            921 non-null    str
 16  landmark                        805 non-null    str
 17  status                          1000 non-null   str
 18  community_board                 1000 non-null   str
 19  council_district                979 non-null    str
 20  police_precinct                 1000 non-null   str
 21  bbl                             875 non-null    str
 22  borough                         1000 non-null   str
 23  x_coordinate_state_plane        981 non-null    str
 24  y_coordinate_state_plane        981 non-null    str
 25  open_data_channel_type          1000 non-null   str
 26  park_facility_name              1000 non-null   str
 27  park_borough                    1000 non-null   str
 28  latitude                        981 non-null    str
 29  longitude                       981 non-null    str
 30  location                        981 non-null    object
 31  :id                             1000 non-null   str
 32  :version                        1000 non-null   str
 33  :created_at                     1000 non-null   str
 34  :updated_at                     1000 non-null   str
 35  :@computed_region_f5dn_yrer     981 non-null    str
 36  :@computed_region_yeji_bk3q     981 non-null    str
 37  :@computed_region_sbqj_enih     981 non-null    str
 38  :@computed_region_92fq_4b7q     981 non-null    str
 39  descriptor_2                    373 non-null    str
 40  vehicle_type                    30 non-null     str
 41  closed_date                     360 non-null    str
 42  resolution_description          440 non-null    str
 43  resolution_action_updated_date  440 non-null    str
 44  taxi_pick_up_location           26 non-null     str
 45  facility_type                   18 non-null     str
 46  bridge_highway_name             6 non-null      str
 47  bridge_highway_direction        6 non-null      str
 48  road_ramp                       5 non-null      str
 49  bridge_highway_segment          6 non-null      str
dtypes: object(1), str(49)
memory usage: 390.8+ KB

In [19]:
df.isna().sum()

unique_key                          0
created_date                        0
agency                              0
agency_name                         0
complaint_type                      0
descriptor                          0
location_type                      48
incident_zip                        7
incident_address                   27
street_name                        27
cross_street_1                    102
cross_street_2                    105
intersection_street_1             102
intersection_street_2             105
address_type                        5
city                               79
landmark                          195
status                              0
community_board                     0
council_district                   21
police_precinct                     0
bbl                               125
borough                             0
x_coordinate_state_plane           19
y_coordinate_state_plane           19
open_data_channel_type              0
park_facility_name                  0
park_borough                        0
latitude                           19
longitude                          19
location                           19
:id                                 0
:version                            0
:created_at                         0
:updated_at                         0
:@computed_region_f5dn_yrer        19
:@computed_region_yeji_bk3q        19
:@computed_region_sbqj_enih        19
:@computed_region_92fq_4b7q        19
descriptor_2                      627
vehicle_type                      970
closed_date                       640
resolution_description            560
resolution_action_updated_date    560
taxi_pick_up_location             974
facility_type                     982
bridge_highway_name               994
bridge_highway_direction          994
road_ramp                         995
bridge_highway_segment            994
dtype: int64

In [20]:
df.head(3).T

,0,1,2
unique_key,70024641,70021357,70022914
created_date,2026-08-11T01:51:06.000,2026-08-11T01:50:41.000,2026-08-11T01:50:01.000
agency,NYPD,NYPD,NYPD
agency_name,New York City Police Department,New York City Police Department,New York City Police Department
complaint_type,Illegal Parking,Illegal Parking,Blocked Driveway
descriptor,Blocked Hydrant,Posted Parking Sign Violation,No Access
location_type,Street/Sidewalk,Street/Sidewalk,Street/Sidewalk
incident_zip,10451,10001,11435
incident_address,2403 3 AVENUE,601 WEST 29 STREET,95-07 CRESSKILL PLACE
street_name,3 AVENUE,WEST 29 STREET,CRESSKILL PLACE
cross_street_1,DEAD END,11 AVENUE,95 AVENUE
cross_street_2,3 AVENUE BRIDGE BIKE PATH,12 AVENUE,97 AVENUE
intersection_street_1,DEAD END,11 AVENUE,95 AVENUE
intersection_street_2,3 AVENUE BRIDGE BIKE PATH,12 AVENUE,97 AVENUE
address_type,ADDRESS,ADDRESS,ADDRESS
city,BRONX,NEW YORK,JAMAICA
landmark,3 AVENUE,WEST 29 STREET,CRESSKILL PLACE
status,In Progress,In Progress,In Progress
community_board,01 BRONX,04 MANHATTAN,12 QUEENS
council_district,08,03,27
police_precinct,Precinct 40,Precinct 10,Precinct 103
bbl,2023190112,1006750012,4100060001
borough,BRONX,MANHATTAN,QUEENS
x_coordinate_state_plane,1003343,982953,1036784
y_coordinate_state_plane,233789,213551,193230
open_data_channel_type,MOBILE,MOBILE,PHONE
park_facility_name,Unspecified,Unspecified,Unspecified
park_borough,BRONX,MANHATTAN,QUEENS
latitude,40.80835201443568,40.75282460038294,40.696892555973484
longitude,-73.93102990983091,-74.00468127751485,-73.81054733288961
location,"{'type': 'Point', 'coordinates': [-73.93102990...","{'type': 'Point', 'coordinates': [-74.00468127...","{'type': 'Point', 'coordinates': [-73.81054733..."
:id,row-i8n6-n862.amqy,row-6huf-9wfr~hsme,row-3rtj~7tmx~m876
:version,rv-a2v7~b7gw~3hyj,rv-se53_f2nt-q2bq,rv-4ttm.f64s-dj3n
:created_at,2026-08-12T01:33:37.158Z,2026-08-12T01:33:37.158Z,2026-08-12T01:33:37.158Z
:updated_at,2026-08-12T01:54:30.420Z,2026-08-12T01:54:03.236Z,2026-08-12T01:54:03.236Z
:@computed_region_f5dn_yrer,49,12,41
:@computed_region_yeji_bk3q,5,4,3
:@computed_region_sbqj_enih,23,6,61
:@computed_region_92fq_4b7q,35,10,46
descriptor_2,NaN,NaN,NaN
vehicle_type,NaN,NaN,NaN
closed_date,NaN,NaN,NaN
resolution_description,NaN,NaN,NaN
resolution_action_updated_date,NaN,NaN,NaN
taxi_pick_up_location,NaN,NaN,NaN
facility_type,NaN,NaN,NaN
bridge_highway_name,NaN,NaN,NaN
bridge_highway_direction,NaN,NaN,NaN
road_ramp,NaN,NaN,NaN
bridge_highway_segment,NaN,NaN,NaN

In [7]:
(df.isna().sum() / len(df) * 100).sort_values(ascending=False)

road_ramp                         99.5
bridge_highway_name               99.4
bridge_highway_segment            99.4
bridge_highway_direction          99.4
facility_type                     98.2
taxi_pick_up_location             97.4
vehicle_type                      97.0
closed_date                       64.0
descriptor_2                      62.7
resolution_description            56.0
resolution_action_updated_date    56.0
landmark                          19.5
bbl                               12.5
cross_street_2                    10.5
intersection_street_2             10.5
cross_street_1                    10.2
intersection_street_1             10.2
city                               7.9
location_type                      4.8
incident_address                   2.7
street_name                        2.7
council_district                   2.1
:@computed_region_sbqj_enih        1.9
:@computed_region_92fq_4b7q        1.9
y_coordinate_state_plane           1.9
x_coordinate_state_plane           1.9
:@computed_region_yeji_bk3q        1.9
longitude                          1.9
location                           1.9
:@computed_region_f5dn_yrer        1.9
latitude                           1.9
incident_zip                       0.7
address_type                       0.5
unique_key                         0.0
status                             0.0
complaint_type                     0.0
agency_name                        0.0
agency                             0.0
descriptor                         0.0
created_date                       0.0
:created_at                        0.0
open_data_channel_type             0.0
police_precinct                    0.0
:version                           0.0
:id                                0.0
park_facility_name                 0.0
park_borough                       0.0
community_board                    0.0
borough                            0.0
:updated_at                        0.0
dtype: float64

In [8]:
df.dtypes

unique_key                           str
created_date                         str
agency                               str
agency_name                          str
complaint_type                       str
descriptor                           str
location_type                        str
incident_zip                         str
incident_address                     str
street_name                          str
cross_street_1                       str
cross_street_2                       str
intersection_street_1                str
intersection_street_2                str
address_type                         str
city                                 str
landmark                             str
status                               str
community_board                      str
council_district                     str
police_precinct                      str
bbl                                  str
borough                              str
x_coordinate_state_plane             str
y_coordinate_state_plane             str
open_data_channel_type               str
park_facility_name                   str
park_borough                         str
latitude                             str
longitude                            str
location                          object
:id                                  str
:version                             str
:created_at                          str
:updated_at                          str
:@computed_region_f5dn_yrer          str
:@computed_region_yeji_bk3q          str
:@computed_region_sbqj_enih          str
:@computed_region_92fq_4b7q          str
descriptor_2                         str
vehicle_type                         str
closed_date                          str
resolution_description               str
resolution_action_updated_date       str
taxi_pick_up_location                str
facility_type                        str
bridge_highway_name                  str
bridge_highway_direction             str
road_ramp                            str
bridge_highway_segment               str
dtype: object

In [9]:
(df.isna().sum()/len(df) * 100).sort_values(ascending=False).head(10)

road_ramp                   99.5
bridge_highway_name         99.4
bridge_highway_segment      99.4
bridge_highway_direction    99.4
facility_type               98.2
taxi_pick_up_location       97.4
vehicle_type                97.0
closed_date                 64.0
descriptor_2                62.7
resolution_description      56.0
dtype: float64

In [10]:
df.columns[df.isna().mean() >= 0.99].tolist()

['bridge_highway_name',
 'bridge_highway_direction',
 'road_ramp',
 'bridge_highway_segment']

In [9]:
df[[
    "created_date",
    "closed_date",
    "status",
    ":updated_at",
    "complaint_type"
]].head(50)

,created_date,closed_date,status,:updated_at,complaint_type
0,2026-08-11T01:51:06.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Illegal Parking
1,2026-08-11T01:50:41.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Illegal Parking
2,2026-08-11T01:50:01.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Blocked Driveway
3,2026-08-11T01:49:10.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Rodent
4,2026-08-11T01:49:09.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Illegal Posting
5,2026-08-11T01:49:00.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Obstruction
6,2026-08-11T01:48:34.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Illegal Parking
7,2026-08-11T01:48:22.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Street/Sidewalk
8,2026-08-11T01:48:22.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Water Maintenance
9,2026-08-11T01:48:21.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Noise - Street/Sidewalk
10,2026-08-11T01:47:55.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Blocked Driveway
11,2026-08-11T01:47:34.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Noise - Commercial
12,2026-08-11T01:47:33.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Abandoned Vehicle
13,2026-08-11T01:47:06.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Illegal Parking
14,2026-08-11T01:46:27.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Illegal Parking
15,2026-08-11T01:46:02.000,NaN,In Progress,2026-08-12T01:53:28.038Z,Water Maintenance
16,2026-08-11T01:44:41.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Street/Sidewalk
17,2026-08-11T01:44:37.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Residential
18,2026-08-11T01:44:14.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Street/Sidewalk
19,2026-08-11T01:43:57.000,NaN,In Progress,2026-08-12T01:53:28.038Z,Dirty Condition
20,2026-08-11T01:43:25.000,NaN,In Progress,2026-08-12T01:53:28.038Z,Blocked Driveway
21,2026-08-11T01:43:05.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Blocked Driveway
22,2026-08-11T01:42:22.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Food Poisoning
23,2026-08-11T01:41:45.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Consumer Complaint
24,2026-08-11T01:41:09.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Residential
25,2026-08-11T01:40:52.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Noise - Residential
26,2026-08-11T01:40:43.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Street/Sidewalk
27,2026-08-11T01:40:14.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Illegal Posting
28,2026-08-11T01:39:35.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Drug Activity
29,2026-08-11T01:38:54.000,NaN,In Progress,2026-08-12T01:53:28.038Z,Water Maintenance
30,2026-08-11T01:38:54.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Street/Sidewalk
31,2026-08-11T01:38:01.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Illegal Parking
32,2026-08-11T01:37:06.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Encampment
33,2026-08-11T01:36:14.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Non-Emergency Police Matter
34,2026-08-11T01:36:13.000,2026-08-11T01:44:34.000,Closed,2026-08-12T01:53:28.038Z,Noise - Residential
35,2026-08-11T01:36:12.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Illegal Parking
36,2026-08-11T01:36:03.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Residential
37,2026-08-11T01:35:08.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Illegal Parking
38,2026-08-11T01:34:51.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Noise - Residential
39,2026-08-11T01:34:47.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Illegal Parking
40,2026-08-11T01:34:44.000,NaN,In Progress,2026-08-12T01:53:28.038Z,Maintenance or Facility
41,2026-08-11T01:34:23.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Illegal Parking
42,2026-08-11T01:33:18.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Illegal Posting
43,2026-08-11T01:32:46.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Residential
44,2026-08-11T01:32:36.000,NaN,In Progress,2026-08-12T01:53:28.038Z,Water Maintenance
45,2026-08-11T01:31:48.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Water Maintenance
46,2026-08-11T01:31:39.000,NaN,In Progress,2026-08-12T01:54:30.420Z,Dirty Condition
47,2026-08-11T01:31:19.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Noise - Street/Sidewalk
48,2026-08-11T01:30:39.000,2026-08-11T01:44:34.000,Closed,2026-08-12T01:54:30.420Z,Drug Activity
49,2026-08-11T01:29:56.000,NaN,In Progress,2026-08-12T01:54:03.236Z,Unleashed Dog

Análise dos dados

In [10]:
df["status"].value_counts(dropna=False)

status
In Progress    526
Closed         359
Open           115
Name: count, dtype: int64

In [26]:
sum(df["closed_date"].isnull())

640

In [27]:
df[df["status"] == "Closed"]["closed_date"].isnull().sum()

np.int64(0)

In [5]:
df[df["status"] != "Closed"][df["closed_date"].notnull()]

C:\Users\kalpi\AppData\Local\Temp\ipykernel_32628\525570341.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df["status"] != "Closed"][df["closed_date"].notnull()]

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,...,vehicle_type,closed_date,resolution_description,resolution_action_updated_date,taxi_pick_up_location,facility_type,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment
853,70014403,2026-08-10T22:21:46.000,DEP,Department of Environmental Protection,Noise,Construction,Building/Construction Site,11434,129-37 153 STREET,153 STREET,...,NaN,2026-08-10T22:53:00.000,The Department of Environmental Protection has...,2026-08-11T00:14:51.000,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.loc[
    (df["status"] != "Closed") & (df["closed_date"].notnull()),
    ["unique_key", "status", "created_date", "closed_date", ":updated_at"]
]

,unique_key,status,created_date,closed_date,:updated_at
853,70014403,In Progress,2026-08-10T22:21:46.000,2026-08-10T22:53:00.000,2026-08-12T01:53:28.038Z

In [21]:
df.loc[
(df["status"] == "Closed") & (df["closed_date"].isnull())]

Empty DataFrame
Columns: [unique_key, created_date, agency, agency_name, complaint_type, descriptor, location_type, incident_zip, incident_address, street_name, cross_street_1, cross_street_2, intersection_street_1, intersection_street_2, address_type, city, landmark, status, community_board, council_district, police_precinct, bbl, borough, x_coordinate_state_plane, y_coordinate_state_plane, open_data_channel_type, park_facility_name, park_borough, latitude, longitude, location, :id, :version, :created_at, :updated_at, :@computed_region_f5dn_yrer, :@computed_region_yeji_bk3q, :@computed_region_sbqj_enih, :@computed_region_92fq_4b7q, descriptor_2, vehicle_type, closed_date, resolution_description, resolution_action_updated_date, taxi_pick_up_location, facility_type, bridge_highway_name, bridge_highway_direction, road_ramp, bridge_highway_segment]
Index: []

[0 rows x 50 columns]

In [6]:
df["complaint_type"].value_counts(dropna=False)

complaint_type
Noise - Residential               195
Illegal Parking                   189
Noise - Street/Sidewalk           108
Water Maintenance                  50
Blocked Driveway                   49
                                 ...
Unsanitary Animal Pvt Property      1
Beach/Pool/Sauna Complaint          1
Violation of Park Rules             1
SAFETY                              1
Missed Collection                   1
Name: count, Length: 67, dtype: int64

In [27]:
df["complaint_type"].nunique()

67

In [13]:
df["agency"].value_counts()

agency
NYPD     617
DEP      104
HPD       71
DOT       59
DSNY      41
DPR       34
DOHMH     32
TLC       26
DHS       10
DCWP       5
OOS        1
Name: count, dtype: int64

In [16]:
df["agency"].isnull().sum()

np.int64(0)

In [14]:
df["agency"].nunique()

11

In [17]:
df.groupby("agency")["agency_name"].nunique()

agency
DCWP     1
DEP      1
DHS      1
DOHMH    1
DOT      1
DPR      1
DSNY     1
HPD      1
NYPD     1
OOS      1
TLC      1
Name: agency_name, dtype: int64

In [20]:
df["created_date"].isnull().sum()

np.int64(0)

In [21]:
df["closed_date"].isnull().sum()

np.int64(640)

In [22]:
df.loc[
    (df["status"] == "Closed") & (df["closed_date"].isnull())
]

Empty DataFrame
Columns: [unique_key, created_date, agency, agency_name, complaint_type, descriptor, location_type, incident_zip, incident_address, street_name, cross_street_1, cross_street_2, intersection_street_1, intersection_street_2, address_type, city, landmark, status, community_board, council_district, police_precinct, bbl, borough, x_coordinate_state_plane, y_coordinate_state_plane, open_data_channel_type, park_facility_name, park_borough, latitude, longitude, location, :id, :version, :created_at, :updated_at, :@computed_region_f5dn_yrer, :@computed_region_yeji_bk3q, :@computed_region_sbqj_enih, :@computed_region_92fq_4b7q, descriptor_2, vehicle_type, closed_date, resolution_description, resolution_action_updated_date, taxi_pick_up_location, facility_type, bridge_highway_name, bridge_highway_direction, road_ramp, bridge_highway_segment]
Index: []

[0 rows x 50 columns]

In [ ]:
df[["created_date", "closed_date"]].head(10)

              created_date closed_date
0  2026-08-11T01:51:06.000         NaN
1  2026-08-11T01:50:41.000         NaN
2  2026-08-11T01:50:01.000         NaN
3  2026-08-11T01:49:10.000         NaN
4  2026-08-11T01:49:09.000         NaN
5  2026-08-11T01:49:00.000         NaN
6  2026-08-11T01:48:34.000         NaN
7  2026-08-11T01:48:22.000         NaN
8  2026-08-11T01:48:22.000         NaN
9  2026-08-11T01:48:21.000         NaN

In [4]:
pd.to_datetime(df["created_date"])

0     2026-08-11 01:51:06
1     2026-08-11 01:50:41
2     2026-08-11 01:50:01
3     2026-08-11 01:49:10
4     2026-08-11 01:49:09
              ...
995   2026-08-10 22:00:22
996   2026-08-10 22:00:19
997   2026-08-10 22:00:19
998   2026-08-10 22:00:02
999   2026-08-10 21:59:58
Name: created_date, Length: 1000, dtype: datetime64[us]

Conversão de str para datetime

In [4]:
df["created_date"] = pd.to_datetime(df["created_date"])

In [5]:
df["created_date"].dtype

dtype('<M8[us]')

In [6]:
df["closed_date"] = pd.to_datetime(df["closed_date"])

In [7]:
df["closed_date"].dtype

dtype('<M8[us]')

In [12]:
(df["closed_date"] - df["created_date"]).sort_values(ascending=False)

921   0 days 03:36:00
999   0 days 03:27:23
905   0 days 03:26:15
907   0 days 03:23:30
750   0 days 03:10:25
            ...
990               NaT
991               NaT
993               NaT
996               NaT
998               NaT
Length: 1000, dtype: timedelta64[us]

In [8]:
df["resolution_time"] = df["closed_date"] - df["created_date"]

In [10]:
df["resolution_time"].dtype

dtype('<m8[us]')

In [41]:
df["resolution_time"].describe()

count                       360
mean     0 days 01:04:42.647222
std      0 days 00:54:26.923218
min             0 days 00:00:01
25%             0 days 00:18:58
50%      0 days 00:45:55.500000
75%      0 days 01:42:51.500000
max             0 days 03:36:00
Name: resolution_time, dtype: object

In [19]:
df["resolution_time"].loc[
df["resolution_time"] > df["resolution_time"].median()]

143   0 days 00:51:38
161   0 days 00:47:06
180   0 days 00:48:49
184   0 days 00:53:24
199   0 days 01:02:00
            ...
992   0 days 01:11:50
994   0 days 03:04:33
995   0 days 02:22:45
997   0 days 03:08:36
999   0 days 03:27:23
Name: resolution_time, Length: 180, dtype: timedelta64[us]

In [10]:
df.loc[
    df["resolution_time"] > df["resolution_time"].median(), "resolution_time"].mean()

Timedelta('0 days 01:48:49.050000')

In [11]:
df.loc[
    df["resolution_time"] <= df["resolution_time"].median(), "resolution_time"].mean()

Timedelta('0 days 00:20:36.244444')

In [12]:
df.loc[
    df["resolution_time"] > df["resolution_time"].median(), "complaint_type"].value_counts()

complaint_type
Illegal Parking                60
Noise - Residential            49
Noise - Street/Sidewalk        29
Noise - Vehicle                10
Blocked Driveway                9
Noise - Commercial              5
Homeless Person Assistance      4
Encampment                      4
Abandoned Vehicle               3
Noise - Park                    2
Panhandling                     1
Animal-Abuse                    1
Traffic Signal Condition        1
Drug Activity                   1
Non-Emergency Police Matter     1
Name: count, dtype: int64

In [45]:
df.loc[
    df["resolution_time"] <= df["resolution_time"].median(), "complaint_type"].value_counts()

complaint_type
Noise - Residential        53
Water Maintenance          37
Noise - Street/Sidewalk    35
Illegal Parking            25
Blocked Driveway           11
Noise - Commercial          6
Encampment                  3
Noise - Vehicle             2
Noise - Park                2
Drug Activity               1
Animal in a Park            1
Street Condition            1
Abandoned Vehicle           1
Noise                       1
Violation of Park Rules     1
Name: count, dtype: int64

In [21]:
df.groupby("complaint_type")["resolution_time"].mean().sort_values(ascending=False)

complaint_type
Non-Emergency Police Matter             0 days 03:05:05
Homeless Person Assistance              0 days 01:49:17
Animal-Abuse                            0 days 01:40:39
Noise - Vehicle                  0 days 01:34:16.333333
Encampment                       0 days 01:33:53.714285
                                          ...
Taxi Complaint                                      NaT
UNSANITARY CONDITION                                NaT
Unleashed Dog                                       NaT
Unsanitary Animal Pvt Property                      NaT
WATER LEAK                                          NaT
Name: resolution_time, Length: 67, dtype: timedelta64[us]

In [29]:
df.groupby("complaint_type")["resolution_time"].count().sort_values(ascending=False)

complaint_type
Noise - Residential               102
Illegal Parking                    85
Noise - Street/Sidewalk            64
Water Maintenance                  37
Blocked Driveway                   20
                                 ...
Taxi Complaint                      0
Unleashed Dog                       0
UNSANITARY CONDITION                0
Unsanitary Animal Pvt Property      0
WATER LEAK                          0
Name: resolution_time, Length: 67, dtype: int64

In [33]:
df.columns.tolist()

['unique_key',
 'created_date',
 'agency',
 'agency_name',
 'complaint_type',
 'descriptor',
 'location_type',
 'incident_zip',
 'incident_address',
 'street_name',
 'cross_street_1',
 'cross_street_2',
 'intersection_street_1',
 'intersection_street_2',
 'address_type',
 'city',
 'landmark',
 'status',
 'community_board',
 'council_district',
 'police_precinct',
 'bbl',
 'borough',
 'x_coordinate_state_plane',
 'y_coordinate_state_plane',
 'open_data_channel_type',
 'park_facility_name',
 'park_borough',
 'latitude',
 'longitude',
 'location',
 ':id',
 ':version',
 ':created_at',
 ':updated_at',
 ':@computed_region_f5dn_yrer',
 ':@computed_region_yeji_bk3q',
 ':@computed_region_sbqj_enih',
 ':@computed_region_92fq_4b7q',
 'descriptor_2',
 'vehicle_type',
 'closed_date',
 'resolution_description',
 'resolution_action_updated_date',
 'taxi_pick_up_location',
 'facility_type',
 'bridge_highway_name',
 'bridge_highway_direction',
 'road_ramp',
 'bridge_highway_segment',
 'resolution_time']

In [64]:
df.groupby("borough")["unique_key"].count().sort_values(ascending=False)

borough
BROOKLYN         314
QUEENS           223
MANHATTAN        214
BRONX            203
STATEN ISLAND     46
Name: unique_key, dtype: int64

In [16]:
df["created_date"].min(), df["created_date"].max()

('2026-09-13T22:35:40.000', '2026-09-14T03:04:12.000')